version: "3.9"

services:
  backend:
    build:
      context: ./backend/FlightApi1.0
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/breakableToy2
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
    environment:
    - NEXT_PUBLIC_API_URL=http://backend:8080
